### ISSUE TITLE
The same function button is displayed repeatedly in similar positions with different appearances

### ISSUE THREAD

**Issue by PolarisGitYHNL** [immich-app/immich#10250]
### The bug

For the convenience of developers, I switched the language display to English, but the issue is the same in the Simplified Chinese interface (other languages should be the same, but I did not test it).
As shown in the following figure, the buttons for restoring default settings, logging out of all devices, etc. appear twice in the vicinity of the left and right sides, one with a text appearance and the other with a button appearance:
<img width="843" alt="image" src="https://github.com/immich-app/immich/assets/165972224/94718f60-15e7-4c59-bc2f-e443e2142867">
<img width="837" alt="image" src="https://github.com/immich-app/immich/assets/165972224/780a2ee3-03cd-4c63-949c-69f879b0a344">

### The OS that Immich Server is running on

Synology DSM docker

### Version of Immich Server

v1.106.3

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Perhaps the problem is unrelated to this
```

### Your .env content

```Shell
Perhaps the problem is unrelated to this
```

### Reproduction steps

```bash
None
```

**Comment by michelheusschen** [comment]
<img width="843" alt="image" src="https://github.com/immich-app/immich/assets/165972224/94718f60-15e7-4c59-bc2f-e443e2142867">
These buttons serve different functions. "Reset" removes any changes since the last save, while "Reset to default" restores all settings to their original default value.


<img width="837" alt="image" src="https://github.com/immich-app/immich/assets/165972224/780a2ee3-03cd-4c63-949c-69f879b0a344">
The text on the left may be unnecessary and could be removed

**Comment by PolarisGitYHNL** [comment]
Tks,I've know that.

**Comment by PolarisGitYHNL** [comment]
Don't forget to remove "LOG OUT ALL DEVICES".
