### ISSUE TITLE
The "IMMICH_SERVER_URL" variable is not set

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#1141]
The following warning is logged by docker compose:

```
WARN[0000] The "IMMICH_SERVER_URL" variable is not set. Defaulting to a blank string.
```

The entry is commented out by default in the `.env` and is clearly marked as optional:

https://github.com/immich-app/immich/blob/38bf310eacdd6a0b03451f63361272b04227a88a/docker/.env.example#L74-L83

Since Immich is running fine, I think the warning can be ignored. But this could confuse users if a warning is logged even if they have configured everything correctly.

docker compose version: v2.14.1

**Comment by jrasm91** [comment]
This is a warning from docker compose, which happens when an environment variable is referenced in the compose file, but a value wasn't provided. We can either (1) update the docs to make this more clear or (2) automatically default the value to an empty string, which may prevent the warning from showing in the first place.
