### ISSUE TITLE
[Feature]: preserve filename template while downloading photos/albums

### ISSUE THREAD

**Issue by marviins87** [immich-app/immich#1159]
### Feature detail

I was very happy to read that the user-defined storage templates were finally there because now i'm able to use the album function to simulate my photo gallery layout of my filesystem. But unfortunately the filenames aren't preserved when downloading a photo or album from Immich. It's reverted back to the original filename instead.
  
E.g. I've uploaded `IMG_1234.JPG` and using template "`{{y}}/{{y}}-{{MM}}/{{y}}{{MM}}{{dd}}_{{filename}}`" it's saved to the filesystem as `20221222_IMG_1234.JPG`. When i download the photo (or an entire album) the photo is renamed back to `IMG_1234.JPG`.

Can we please respect the filename templates?

### Platform

Web

**Comment by alextran1502** [comment]
Yes, this is a reasonable request. Will do

**Comment by stickflowerfightclub** [comment]
Hi, any news about this issue please?
When I download a picture from Immich, I have the same problem: the picture is downloaded with its original name (e.g., whatsapp_img_3232.jpg) instead of the filename template I set up.

My Immich server is up to date of course (v2.3.1).

Many thanks in advance !
