### ISSUE TITLE
Face detection fails when face is rotated 90 degrees and behind another person

### ISSUE THREAD

**Issue by FluffyDiscord** [immich-app/immich#11693]
### The bug

I took a photo of my family and I snuck behind my friend and my head sticks from his left side, facing the camera at -90 degrees (it looks like my head is comming from his side).

Face detection failed to pick my face, even though it's clearly visible. It's my whole head, without neck.

### The OS that Immich Server is running on

Slackware (UNRAID)

### Version of Immich Server

1.111.0

### Version of Immich Mobile App

1.111.0 build.152

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant (?)/default
```

### Your .env content

```Shell
Not relevant (?)/default
```

### Reproduction steps

```bash
1. Upload a photo
2. Wait a bit
3. Face detection fails to detect the face
```

**Comment by bo0tzz** [comment]
cc @mertalev, I think I recently also heard mention of detection failing on an upside-down face. Does the alignment not account for rotation?

**Comment by mertalev** [comment]
Face alignment is exactly to normalize a face to upright position to improve the results of the facial recognition model.

But it doesn't affect whether a face is detected in the first place. It probably did detect the face as a candidate, but it scored too low and got filtered out. I'm not sure if we can really consider that a bug - no model will have 100% accuracy.

**Comment by RaulGw4** [comment]
I also witnessed something similar.

I took two photos, and for some reason, one is rotated 90 degrees. The photos were taken in the exact same place, with no significant differences between them. The person is in plain sight, the quality is as good as it can be, yet it still failed to identify them as a person.

There seems to be an issue somewhere because when I rotate the picture, it identifies the person just fine every time.

**Comment by FluffyDiscord** [comment]
Would it be possible to add option to rotate photo 4 times and apply face detection each time, then merge the results?

**Comment by mertalev** [comment]
The image is normalized based on the EXIF orientation, so I think this only affects:

1) Images where only the face/person is rotated
2) Images where the orientation metadata is missing

(2) should ideally be fixed by fixing the images themselves, so that leaves (1).

It *is* possible to run it for different orientations and merge the results, but it makes face detection 4x slower and complicates the implementation. It doesn't seem worth it to handle a niche case like this.

**Comment by mertalev** [comment]
But it isn't taking 4x the time to get a perfect result, just a result that's better in this one respect that may or may not affect a single image in a library. Worse yet, it could increase the chance of a false positive (detecting a face that doesn't exist).

Adding faces manually is planned and is a better suggestion for cases like this IMO.
