### ISSUE TITLE
Star rating for unowned asset is read-only but appears writable

### ISSUE THREAD

**Issue by C-Otto** [immich-app/immich#11829]
### The bug

If I share an album owned by user A with user B, user B is able to see the star rating for those assets. However, user B seems also be able to SET the star rating (the stars change when moving the mouse over them) - but setting the rating does not work.

Either user B should be able to set the rating, or the UI should indicate that this is a read-only property.

### The OS that Immich Server is running on

Debian Stable

### Version of Immich Server

v1.112.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Reproduction steps

1. Create album with user A
2. Share album with user B
3. As user B, set star rating for one of the assets in the album

**Comment by C-Otto** [comment]
Similarly, I see the option to identify people (I see the list of detected-but-not-named persons) for assets that are part of the "share all" feature. I don't see this for shared assets in (my own) albums. When I try to edit a person, though, I get a permission error.

**Comment by stumpigit** [comment]
Thank you. I could reproduce that. The Star Rating component is actually called correct as read-only. So no request is sent when clicking on the stars. But we have not switched off the hover effect in the component when it is read-only. We still need to adjust this, thanks for the tip.

**Comment by flammermann** [comment]
A similar issue occurs if you are using an external library from a volume mounted as read only. The star rating seems to be available but there is an error in the immich_server container that the xmp file could not be created/written.

Since we are on the topic:

1. Is there any plan on allowing star ratings for read only external libraries?
2. It would probably also be a nice feature to allow people I shared an asset with to provide a star rating, which is then shown to me (as the owner of the asset) in the UI in addition to my own rating. (Or maybe even show all people that have access to an asset all ratings from all other people.)
