### ISSUE TITLE
[BUG] Selecting albums to backup is unresponsive

### ISSUE THREAD

**Issue by bt90** [immich-app/immich#1226]
**Describe the bug**
Searching a folder to backup in the Android app takes very long. After typing in the name, the suggestion pops up around 20 seconds later.

**To Reproduce**
1. Have an Android phone with lots of files/folders (~80GB in my case)
2. Open the backup dialog
3. Type in the name of the folder to backup e.g `Camera`
4. Wait for the suggested folder

**Expected behavior**
Let me use a folder picker instead of scanning the whole filesystem.

**System**
- Google Pixel 4a 5G with Android 13
- Mobile App Version: `1.40.0 build.63`

**Comment by bt90** [comment]
Maybe something like this could be used?

https://pub.dev/packages/file_picker

**Comment by alextran1502** [comment]
Can you help provide a video capture? Using the suggested file_picker extension wouldn't work with the rest of the system because the library we use have their own type when it comes to scanning/uploading/using the asset. 

We are improving some of the intensive tasks to run on an `isolated` or a background thread. I believe it would help solve the issue

**Comment by bt90** [comment]
https://drive.google.com/file/d/1eTD-E5p_xfL1Vbr_Dl1Q3M4WUCDJoYd6/view?usp=drivesdk

**Comment by alextran1502** [comment]
Thank you, we are hoping this PR https://github.com/immich-app/immich/pull/1176 will help tackle this issue
