### ISSUE TITLE
Сделайте понятный интерфейс управления библиотекой, путь, выбор устройства.

### ISSUE THREAD

**Issue by fa1ke5** [immich-app/immich#13213]
### The bug

То что есть сейчас это насилие над мозгом, в принципе не ясно куда сервер располагает библиотеку, как ее найти и главное как указать другой путь.
У меня диск с сиcтемой 50 GB, есть несколько RAID разделов, но не могу установить библиотеку туда.
Разработчики вообще в курсе что бывает несколько дисков на сервере????

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

actual release

### Version of Immich Mobile App

v1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

1. https://shape.host/resources/a-comprehensive-guide-on-installing-immich-on-ubuntu-22-04-lts

**Comment by mmomjian** [comment]
> What we have now is violence against the brain, in principle it is not clear where the server places the library, how to find it and most importantly how to specify another path.
> I have a disk with a 50 GB system, there are several RAID partitions, but I can not install the library there.
Do the developers even know that there can be several disks on the server????

It's relatively easy to set the `UPLOAD_LOCATION` in the `.env` file per our documents. If you want more fine grained volumes, you can choose to mount any specific subfolder you want to a location on the host system. Because of the way Docker works, it's not possible for Immich to handle this.
