### ISSUE TITLE
Question on replacement for Photoprism - 

### ISSUE THREAD

**Issue by Rathna-K** [immich-app/immich#1360]
### Feature detail

Hi there, just tried your demo and love the UI. I am trying to find a replacement for my self-hosted Photoprism app and wondering if this is still too early or the app is stable enough to host about 300GB of photos? Also off-topic - other than the recent paywall issues in Photoprism the app seems good so would it make sense to fort that and develop off of it vs. this one if its too early in development? just curious... 

thanks,
RK 

### Platform

Web

**Comment by samip5** [comment]
I kinda like some aspects of the UI on Photoprism and the fact it will regonize faces from pictures and then group them all under that person's name separately.

I currently have both installed.

**Comment by alextran1502** [comment]
Hello, this is up to you. I've been using the app since the beginning and just be mindful of breaking changes between releases. But usually, we provide clear instructions on how to resolve the breaking changes to keep the instance running.

I think the best way to answer the question is for you to try the application for a few weeks and get a feel for it. 

Here is the stats of my production instance 

![image](https://user-images.githubusercontent.com/27055614/213476382-d0eaef08-0fb4-44aa-bb27-94c8a4b6094e.png)

**Comment by Rathna-K** [comment]
> I kinda like some aspects of the UI on Photoprism (that would be nice IMO in Immich too) and the fact it will regonize faces from pictures and then group them all under that person's name separately.
> 
> I currently have both installed.

I agree. 


> Hello, this is up to you. I've been using the app since the beginning and just be mindful of breaking changes between releases. But usually, we provide clear instructions on how to resolve the breaking changes to keep the instance running.
> 
> I think the best way to answer the question is for you to try the application for a few weeks and get a feel for it.
> 
> Here is the stats of my production instance
> 
> ![image](https://user-images.githubusercontent.com/27055614/213476382-d0eaef08-0fb4-44aa-bb27-94c8a4b6094e.png)

for folder structure - can the current structure be used and not go thru automatic renaming and just scan and show the albums?

**Comment by alextran1502** [comment]
Please follow #1006 for more information
