### ISSUE TITLE
[BUG] Mobile action bar is too wide for my thin phone display

### ISSUE THREAD

**Issue by martyfuhry** [immich-app/immich#1735]
### The bug

There are too many action icons in the image gallery on my phone and it's now overflowing.

![image](https://user-images.githubusercontent.com/100457/218281281-58b47580-510d-430c-91fd-aaf0479956ed.png)

### The OS that Immich Server is running on

Android

### Version of Immich Server

1.46.0

### Version of Immich Mobile App

1.46.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. View a HEIC photo with the play button added to the action bar
2. Actions overflow
```

### Additional information

Using a Samsung Galaxy Fold 3 in closed / normal mode.

**Comment by martyfuhry** [comment]
I'm very happy to fix this, but I'd like to open it to some discussion first.

**Comment by alextran1502** [comment]
Below are my thoughts

1. Put `download`, `favorite`, `play motion video` on the top bar. 
2. Put `share`, `add to album` and `delete` to the bottom bar.
3. Revert the change of the info icon to be `horizontal dots` icons
4. Put all options to the top of the detail EXIF view, horizontal scrolling and not show the top and bottom bar once the EXIF bar is shown.

So basically very identical to how GPhotos handles this part by splitting up the top and bottom app bar. 

I wonder if we can mimic the behavior of having the bottom sheet push up the asset instead of overlaying it over the asset.

Please let me know your thoughts.
