### ISSUE TITLE
[Feature]: Show local files if present in App

### ISSUE THREAD

**Issue by tschoesi** [immich-app/immich#188]
### Feature detail

When using the Mobile App, most of the recently uploaded photos are probably still located on the device.
It would be nice if the app could display the local version of the file if it is present (instead of downloading it again from the server). 

This would be very similar to Google Photos, which let's you view any album (local or not), and always shows the local version if possible. This would increase speed and reduce server load.

### Platform

Mobile App

**Comment by alextran1502** [comment]
There is an icon on the lower right corner of the thumbnail on the timeline view that indicates whether or not the asset is on the device or has been deleted. If the asset has been backup and has been deleted from the device, it will have the cloud icon like this 
![image](https://user-images.githubusercontent.com/27055614/170712909-57728e20-9f6d-4a71-a9c2-e1b444b13de5.png)

Otherwise, it will have the "album icon". That is the mechanism I used to distinguish the state of the backup file.

**Comment by tschoesi** [comment]
Yes, I think I understand how this indicator works.
However, when you tap on a picture that has been backed up it is still loaded from the server, right?

It would make more sense to show the local version of the file.

**Comment by alextran1502** [comment]
That is correct. Since the photo is guaranteed to be on the server once it is backed up, it is simpler to fetch the photo from the server, to keep the mechanism as simple as possible, for maintainability sake.

**Comment by SNThrailkill** [comment]
+1 for this feature. It's really the last thing holding me back from using a 3rd party app 100% of the time and is something that only Immich could do since most other photo managers like photoprism only have a PWA and wouldn't be able to include this functionality. Might be worth prioritizing.

**Comment by alextran1502** [comment]
> +1 for this feature. It's really the last thing holding me back from using a 3rd party app 100% of the time and is something that only Immich could do since most other photo managers like photoprism only have a PWA and wouldn't be able to include this functionality. Might be worth prioritizing.

Pr #905 is in the work for this
