### ISSUE TITLE
[BUG] Immich doesn't notify of duplicate uploads

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2557]
### The bug

Nothing happens when attempting to upload a file which already exists. It would be nice if there was some feedback which said it was successful or that it is a duplicate rather than just doing nothing.

```json
{"isExist":true,"id":"703b63e9-a71d-4b5c-8149-0bd6d45010bd"}
```

### The OS that Immich Server is running on

Arch Linux

### Version of Immich Server

1.57.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Upload a file.
2. Upload the same file again.
3. Observe nothing happens.
```

**Comment by Sherlock1979** [comment]
Same for CLI. When uploading assets and then manually comparing number of files I noticed a small mismatch (in my case 46 of 22k photos). I thought that upload failed and rerun it a few times but nothing changed. 

According to CLI there were 0 errors.

Alex pointed out that these 46 assets may be duplicates and he was correct indeed.

So, as you rightly said, even in the CLI "It would be nice if there was some feedback which said it was successful or that it is a duplicate rather than just doing nothing."

**Comment by DX37** [comment]
I had to reinstall Immich after firmware factory reset, and then app proceeds to upload all my photos all over again and duplicates them.
