### ISSUE TITLE
mobile: cannot download photos from shared album

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2976]
### The bug

To reproduce:
1. Create a shared album with photos.
2. Try to download a photo from the shared album.

An download error should appear.

![image](https://github.com/immich-app/immich/assets/9749173/a45eace3-6115-487f-ad05-0d2b5b7e9d64)

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

1.63.0 build.103

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by r01k** [comment]
> Experiencing the same issue on Android and iOS...

Same here. Attempting to share or download any photos apparently succeeds but results in an empty image. Interestingly, my girlfriend's Android phone has no issue. She has a separate Immich account. A third user on iOS also sees the "Download error" message as well.

That said, I don't think we are describing the exact same problem reported on this issue because we don't see any error on the app or relevant logs even with highest logging level. I may log a separate issue after digging deeper.

**Comment by r01k** [comment]
Update: I had installed from FDroid. Uninstalled and reinstalled from the Google Play Store and the problem doesn't happen. Confirmed it on two devices. My girlfriend had installed from the Play Store from the getgo and she never saw the empty download problem.

**Comment by Akash006** [comment]
I'm still facing the same problem on 3 devices. 2 Android and 1 IOS

**Comment by jrasm91** [comment]
This looks to be fixed as I could not reproduce it.
