### ISSUE TITLE
mobile: should be more resilient to temporary communication issues

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2980]
### The bug

I use Tailscale to access Immich, and have an iOS automation which connects to Tailscale when I open the app. I found that Immich will try to resolve the host, fail, and then assume I'm actually unauthenticated and ask me to login again. It would be nice to:
1. Not make that assumption.
2. Handle transient connection failures more gracefully.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

1.63.0 build.103

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by awonglk** [comment]
Curious if there is any plans to fix this issue? 
It does impact background jobs whenever it's logged out, thus no photos are backed up until I open the app to login again.

**Comment by ddshd** [comment]
> Curious if there is any plans to fix this issue? It does impact background jobs whenever it's logged out, thus no photos are backed up until I open the app to login again.

Some of the changes I’ve made should have helped with this.

Could you help me with if you’re using a domain or direct IP in the app?

**Comment by awonglk** [comment]
I am using a domain name

**Comment by traktuner** [comment]
Same problem here. Not using Tailscale. Domain name (subdomain) with Let's Encrypt cert.
It happens every time I update the docker image. When the server is "not ready yet" and someone opens immich, it logs out. User has to log in again. Seems like that happens when you get a 502 back.
Maybe implement a "server not reachable" screen and retry in the background?
All my users are on iOS, all have the same problem including me.

**Comment by bt90** [comment]
Fixed by #7383

**Comment by rawcomposition** [comment]
Just started using the app a couple days ago and I've already been logged out 3 or 4 times for no apparent reason.

**Comment by rawcomposition** [comment]
![Screenshot 2024-04-23 at 7 07 27 AM](https://github.com/immich-app/immich/assets/740090/7ca9dcd2-6f8f-44a9-a352-14ca63a79e45)

The Immich instance was online the whole time, and logging in manually worked fine, so presumably it was a temporary outage I guess, hard to say what caused that. But would be great if it wouldn't log out every time there's a temporary outage.

**Comment by itaintgonnawell** [comment]
In my case, free ddns service(duckdns) is sometimes down, unreachable some minutes or about an hour, and then iOS immich app automatically logged out when immich tries to background task or ping I guess. (Not happened with my iPad app which logged in but background backup not enabled)

Please consider to add 'retry access with delay'
since I think most of users can't notice such background logout and keep considering background backup works.

**Comment by lasdem** [comment]
My wife experiences the same issues on iOS, now twice within 7 days. On Android I did not have this issue yet. 
Last instance correlates with me updating the server, after that she was logged out.

**Comment by bt90** [comment]
While it doesn't solve the underlying problem, the suggestion in #11034 may at least improve usability.
