### ISSUE TITLE
[BUG] -64 Uploads left, stuck on one single motion picture upload

### ISSUE THREAD

**Issue by shanehughes1990** [immich-app/immich#3676]
### The bug

Immich Mobile app syned all 1200ish photos/videos from my device everything except a few,

The backup status on the mobile app says -64 assets remaining, and it seems to be stuck on uploading one singular video.

### The OS that Immich Server is running on

container environment running in kubernetes

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

v1.72.0 build.95

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Run in kubernetes deployed via terraform
```

### Your .env content

```Shell
{
        name  = "IMMICH_MACHINE_LEARNING_URL"
        value = "http://${local.deployment_names.machine_learning}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc:3003"
      },
      {
        name  = "TZ"
        value = "America/Toronto"
      },
    {
      name  = "IMMICH_WEB_URL"
      value = "http://${local.deployment_names.web}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc:3000"
    },
    {
      name  = "IMMICH_SERVER_URL"
      value = "http://${local.deployment_names.server}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc:3001"
    },


database_env = [
    {
      name  = "DB_HOSTNAME"
      value = "${local.deployment_names.database}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc"
    },
    {
      name  = "DB_PORT"
      value = 5432
    },
    {
      name  = "DB_USERNAME"
      value = var.postgres_config.username
    },
    {
      name      = "DB_PASSWORD"
      value     = var.postgres_config.password
      is_secret = true
    },
    {
      name  = "DB_DATABASE"
      value = var.postgres_config.username
    },
    {
      name  = "DB_DATABASE_NAME"
      value = var.postgres_config.username
    },
  ]

  redis_env = [
    {
      name  = "REDIS_HOSTNAME"
      value = "${local.deployment_names.redis}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc"
    },
    {
      name  = "REDIS_PORT"
      value = 6379
    },
    {
      name  = "REDIS_DBINDEX"
      value = 0
    },
  ]

  typesense_env = [
    {
      name  = "TYPESENSE_ENABLED"
      value = true
    },
    {
      name  = "TYPESENSE_HOST"
      value = "${local.deployment_names.typesense}-app-port.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc"
    },
    {
      name  = "TYPESENSE_PORT"
      value = 8108
    },
    {
      name  = "TYPESENSE_PROTOCOL"
      value = "http"
    },
    {
      name      = "TYPESENSE_API_KEY"
      value     = var.typesense_api_key
      is_secret = true
    },
  ]
```

### Reproduction steps

```bash
1. Deploy and configure Immich server setup
2. Install mobile app
3. Start backup and wait
4. After 99% of content was uploaded the remaining assets shows -64 and is now erroring on upload asset
```

**Comment by alextran1502** [comment]
Hello, what is your phone model?

**Comment by shanehughes1990** [comment]
![Screenshot_20230815-140249_Settings.jpg](https://github.com/immich-app/immich/assets/31993465/ae79fd37-4cb5-4534-98f2-4b5bcfa4cac0)

**Comment by shanehughes1990** [comment]
![Screenshot_20230815-140249_Settings.jpg](https://github.com/immich-app/immich/assets/31993465/ae79fd37-4cb5-4534-98f2-4b5bcfa4cac0)

As you may notice I have an immich icon indefinitely there because of the infinite retry to upload and error

**Comment by shanehughes1990** [comment]
Just food for though I did start a backup of all folder assets and in the middle I removed some folders to be synced I'm wondering if the negative number is the result of what it detects needing to be uploaded VS what is left and it's less than the server 🤷

**Comment by rowan-walshe** [comment]
I have the same issue on an iphone 12. After it finished syncing it showed as -4 remaining. It was also attempting to upload some very large videos every time the app opened (I assume because it was failing due to the file sizes, because of the [Cloudflare tunnel size restriction](https://documentation.immich.app/docs/FAQ#why-are-only-photos-and-not-videos-being-uploaded-to-immich)). I found the videos and deleted them as they were just long recordings of my pocket.

Having done this it now shows as -7 remaining, so I wonder if it has something to do with images/videos being on the phone?

**Comment by diogocardoso28** [comment]
Mine is showing -691 and my wife's phone is on a similar number, the diference is that mine doensn't seem to be stuck on any particular photo, uploads all and stops. My phone is a galaxy S23 ultra and my wife's is a s20.  
![Screenshot_20230823_121600](https://github.com/immich-app/immich/assets/65686179/59aa646e-3743-422c-ad2c-82b41e90da65)
![Screenshot_20230823_121529](https://github.com/immich-app/immich/assets/65686179/b613acac-0deb-42f6-a12f-cda7d8df0945)

**Comment by FAT9L** [comment]
Same experience here, although I'm pretty sure that all ~13k images are 100% backed up. 

I *did* manually select a few folders while the generic "recent" category was being backed up, not sure if there's an overlap there that's causing the issue? If I had to guess, it's just a visual bug. 

Nothing in the logs jumps out at me. 

![Screenshot_20230901_174836.png](https://github.com/immich-app/immich/assets/96025485/89de29d6-a836-4720-bb09-06e37d6561f9)

![Screenshot_20230901_174850.png](https://github.com/immich-app/immich/assets/96025485/379e72ff-e79c-4f5b-8e79-95295e0e0705)

Galaxy S22 Ultra (SM-980U1) on Android 13 (August patch).

**Comment by rowan-walshe** [comment]
Disclaimer, I have never written a mobile app, and don't know the api.

That said, I suspect that this is the line that is causing the issue: https://github.com/immich-app/immich/blob/2069293cc1ccc175cd48901a57be869161029ccb/mobile/lib/modules/backup/views/backup_controller_page.dart#L759

It looks like it just counts how many things it has backed up, and subtracts from that how the number of assets it wants to have backed up (i.e. those from the currently selected albums). If you delete a photo/video from your phone, or change the selection of albums/photos to backup, this will reduce the count of things on your device that should be backed up, but the number of things backed up won't change (since it's a backup, it won't delete from the server unless you manually do that, which makes sense).

Instead of just doing a `backed_up_count - local_count`, and if possible given the api, it probably needs to find the set of ids that appear locally, but not in the backup, and then display that count as the number remaining to backup. I assume similar logic is probably already done somewhere to figure out which assets to upload, so could probably be copied from there (looks like the info is maybe in `BackUpState`).

**Comment by someonewating** [comment]
Got a same error. The error just happened after I selected the album and pressed upload, I kept immich at the frontstage and keep my screen light during the uploading, but I still got this error, which immich shows `Remainder: -XXX`.

**Comment by EnochPrime** [comment]
The negative remainder is a known bug: #968

**Comment by wary-hermit** [comment]
> Cloudflare tunnel size restriction  

One of my videos kept uploading and failing on repeat whist making my old ThinkPad go _**brrrrr**_, got a bit crazy trying to a find a reason why. 
Just found out about this limitation - and indeed failing video was above 100MB. Set up app to connect via IP on local LAN - video uploaded successfully. Wanted to say big thanks!

**Comment by fivestones** [comment]
I upgraded the server to 1.9.2 and upgraded the iOS app to 1.9.0 build.130 and the negative numbers all went away. I'm not sure if I did something else that would've made this happen, but nothing that I know of. With the previous version I had a negative number, and now it just says "0" once all the images are uploaded.
