### ISSUE TITLE
Wrong Sorting / Cutoff Faces currently in Front-End not Database

### ISSUE THREAD

**Issue by titro** [immich-app/immich#3709]
### The bug

#3662 does not solve the issue in #3660 for me.

 Some faces are still not shown and now the ordering is also shown some unnamed faces before named faces:

![image](https://github.com/immich-app/immich/assets/4005090/ce1ffbe0-a56d-4dd4-818e-7e5eda532a48)

### The OS that Immich Server is running on

unraid

### Version of Immich Server

v1.73

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. open explore people page
```

**Comment by martabal** [comment]
Do you have hidden faces ?

**Comment by shalong-tanwen** [comment]
> Some faces are still not shown and now the ordering is also shown some unnamed faces before named faces:

Can you please confirm if the un-named faces showing before named have more assets with their face than the named faces following them? I removed the filtering in the server since the results are already sorted, but did not factor the case where the un-named faces might have more assets few named faces 🤦‍♂️
