### ISSUE TITLE
[Feature]: Support audio files

### ISSUE THREAD

**Issue by Eidenz** [immich-app/immich#374]
### Feature detail

I know Immich is mainly focused on images, but I do have a couple audio memories (wav, mp3..) that I'd like to have on Immich as well rather than needing to use a secondary cloud service.

I think this would be a nice feature to have to support all kind of memories.

### Platform

Server

**Comment by zackpollard** [comment]
Personally I don't believe this is really the idea behind Immich and I think it would be quite difficult to implement these in a way that looks nice in the UI alongside the photos and videos as we wouldn't have any way to generate a thumbnail for the file. I'll leave this open to gather more feedback from the other devs but my vote would be against adding this to Immich.

**Comment by Eidenz** [comment]
I think that a simple music note placeholder wouldn't be bothering (especially if you're the one adding it knowingly), but that's an understandable statement.

Proposed it due to the goal being to store memories, and images are only a part of it. Curious about Alex's position on this.

**Comment by alextran1502** [comment]
From the library we use to upload assets from the phone. I remember seeing an options to get audio type asset. I think this can help with uploading such file.

I think it can be done, but it also requires a lot of work on all platform to render/play the content. Since this is a niche feature, I think it will be done at a later day when we finish other major features. 

To help with this, can you help with a guide on how to create an audio memory? Do you know if it is also showed in the gallery?

**Comment by Eidenz** [comment]
I see, that's perfectly fine, I don't have many myself.

I'm not sure to fully understand your request? To get my audio files, they either come from an audio recorder app on my phone, or downloaded online from audio libraries.

Though my bad sorry, it wasn't Google Photos displaying those but another Gallery app I had, never really noticed it switched to it when playing audio files.
So they don't show up in Google Photos, and the other gallery app just had a music note instead of the usual image preview.

**Comment by Eidenz** [comment]
And even though it's under the "Feature request" tag, it was really more of a general question/future feature (after production or something).

Personally, I'm fine converting my audio files to mp4 using something like a music note to generate the preview.

**Comment by alextran1502** [comment]
@Eidenz From my understanding that the audio file is stored in a different location rather than the location photos and videos are stored, so it might be difficult to obtain the file.

**Comment by alextran1502** [comment]
When it comes to this feature, I will let you know more about what I find out.

**Comment by alextran1502** [comment]
After further consideration, this feature won't be implemented as it doesn't fit into the vision of the app.

**Comment by forresthopkinsa** [comment]
I understand why this was closed, but IMO the landscape has changed a little bit in the past few years and it seems like Immich's scope has increased a bit with the uptick in funding. Is this feature request worth reconsidering? Even as a far-future roadmap item?

There are not a lot of options for hosting a gallery of audiovisual media and Immich has (wonderfully!) risen to the point of being the state of the art in this area.

**Comment by earlsrock** [comment]
Here is my use-case on why I would like to have specifically M4A support considered for addition - as well as why it might be low hanging fruit to add more easily.

My kids send our family members pictures, videos, and audio messages.  These get saved as .JPG, .MOV, and .M4A respectively.  I'm using Immich to store all this and make it accessible to myself and family for enjoyment.  I am able to transfer the pictures and videos, but not the audio in M4A format - even though they are treasured memories.  Given that M4A can be boiled down to just an MP4 with no video, the framework for everything to make this work is already there and technically this already works if you rename the M4A file to MP4.  The only "issue" is that once the MP4 is imported - there is no thumbnail for the video-less MP4 in the timeline/gallery.  

By adding only support for M4A, no heavy lifting needs to be done since Immich already works with that file format (just not the extension).  You can just use a placeholder audio image for all thumbnails for M4A files.  As far as where files get stored, they can store in exactly the same location as video files - again since M4A is just an MP4 with no video stream embedded.  Transcoding should work exactly as it already does since it's still just the same audio codec.

I appreciate your consideration.

**Comment by ngdangtu-vn** [comment]
2 / 3 media types are supported by Immich which are image and video. But no audio? I don't see why it doesn't match the app vision?

**Comment by Ahrimdon** [comment]
I don't see why this is such a contentious issue. This is literally aiming to be a self-hosted media server. Image, video, audio... There are tons of ways this can be implemented to look nice along side the other images and videos. It's clearly not Jellyfin and it's obvious just from looking at the UI. It's not like anyone's going to misinterpret the intended use case of the application.

I don't get why the maintainers are trying to make this akin to Apple's walled garden where I have to remux my audio with a single black frame to even get it to save to my camera roll. I paid $10 to support **NOT** having this closed minded attitude 👎

**Comment by alextran1502** [comment]
Oh man, I didn't know we set out to support only photos and videos would make such a big issue 😅. 

How about voicing the feature you want in a bit less vocal and demanding? It helps to keep the team sane and happy and also make your idea easier to listen to 😉.

Our tag line is "self-hosted **photo and video management** solution", but anyway when we are in good shape of shape of supporting video and photo, we might take a peak at supporting audio as well

**Comment by Ahrimdon** [comment]
@alextran1502 

I hate being an asshole or the demanding type, **especially** to those who put in countless hours of hard work for the public's benefit with little return. I'm not typically that kind of guy on the internet or in real life. With that being said, sometimes it takes someone to speak up and say what the hell everyone is thinking and cut through the bullsh*t.

It worked, didn't it? You replied within 30 minutes when people have been trying to get team to at the very least look at this issue again for the last 6 months.

I hope the team takes a sincere look into this, even if it's not enabled by default. A small compromise while adding this feature is better than the app without the feature. Thank you for the response and taking this into consideration. Nothing personal was meant by anything I said, I simply want this app to be the best it can be.

**Comment by alextran1502** [comment]
@Ahrimdon Thanks, I also want to be honest with you that this is not in our roadmap in the near or long term. As time and resources allow, we might look into it. 

Just a note, nothing is simple in programming, and in open-source, no is temporary and yes is forever. So we need to plan and gauge the expectation accordingly

**Comment by rastographics** [comment]
Hi just want to chime in on this. Been using several instances of immich for a couple years, even at our non-profit for digital media library. 

Immich has been a wonderful answer for cloud-based collaboration for creating videos with our in-house media, with a small volunteer team spread out across regions. Nothing can touch it!

In addition to the shared video and photo resources for creating content, I was looking into the possibility to use immich for our audio files as well...voice over recordings, our music, sound effects, etc.

Came across this issue and even though I understand it won't be on the roadmap soon, I wanted to mention this use case as a Digital Asset Manager is out there as well. I know that's not what immich set out to be...but congratulations @alextran1502, because in my opinion, you've made it into one of the best out there regardless!

**Comment by niieani** [comment]
hey folks! would you accept a high quality PR contribution that adds support for audio files?

**Comment by zackpollard** [comment]
> hey folks! would you accept a high quality PR contribution that adds support for audio files?

Hey, I appreciate the willingness to contribute this feature, however currently we have decided not to include this feature in Immich. This may change in the future as the project progresses.

**Comment by 0xf965** [comment]
> hey folks! would you accept a high quality PR contribution that adds support for audio files?

Hey @niieani , thanks a lot for offering that contribution! 🙌
Since the core team decided not to include audio support for now, would you be open to sharing your fork with that feature? I’m sure quite a few of us would find it super useful to try it out even if it’s not in the main repo.

**Comment by niieani** [comment]
Hey @0xf965 , I haven't actually built it yet, I was hoping to get the team's blessing first as forking means I'd have to maintain (keep my fork updated) which isn't something I'm too excited about 😔 
Just hoping the team sees the value in the future for now. If I do decide to fork, I'll post it here. For now I might go with the workaround of wrapping my audio files in an .MP4 container, which should still make them playable in the browser and hopefully works with Immich, even without a video track. But this does mean I have to build a pipeline to process all my audio-only files, which is not ideal.

**Comment by earlsrock** [comment]
> For now I might go with the workaround of wrapping my audio files in an .MP4 container, which should still make them playable in the browser and hopefully works with Immich, even without a video track. 

Can confirm as I use it - audio track only MP4s work fine in Immich.  There is no image thumbnail in the library though as it displays a black thumbnail.  It will just display a black screen when played as well.  Audio works fine though.  I guess you could encode in a "static" image video to your MP4, but that would cause unnecessary bloat to the MP4 size.  Just wanted to let you know it works.

Congrats to the team on hitting Stable!

**Comment by nkrabben** [comment]
I have a lot of audio files that I'd love to be able to access alongside my images and videos. I've been experimenting along the same libes as above, although I've added waveforms to my mp4 rewraps via FFmpeg like this
`ffmpeg -i inputfile -filter_complex "[0:a]showwaves=s=1280x1280:mode=line:colors=white,format=yuv420p[v]" -map "[v]" -map 0:a -c:v libx264 -c:a copy outputfile`

That makes a video of the waveform, which blows up the file size and looks nicer. A single waveform of the entire file would also work and be much smaller.

Otherwise, it fits perfectly with how I use Immich, except for one thing, tagging voices. I can manually add some squares in the video for non-existent faces, but that's very hacky.

However, that's a problem with all videos. Right now, I have no clean way to tag an off-screen voice. In the future, some of this may be covered by time-based facial recognition and speech-to-text, but doing this well may need further development of features to tag unseen people to assets.

**Comment by johnmaguire** [comment]
I would love if Immich supported audio files. Like others, my family has treasured audio recordings that we'd like to share with each other. Immich would be a convenient way to do that.

With regards to the original pushback:

> Personally I don't believe this is really the idea behind Immich and I think it would be quite difficult to implement these in a way that looks nice in the UI alongside the photos and videos as we wouldn't have any way to generate a thumbnail for the file. 

I think this is a very valid concern - one way to deal with it might be to add a separate area for recordings, so they aren't mixed in with audio / video by default.

**Comment by LinasKo** [comment]
Adding another voice to the choir - I'd love this as well!

There's audio logs and fond moments of loved ones I'm looking to preserve. It takes the same space in my heart as the pictures I'm backing up, which ultimately lead me here.

Yet, as a former Open Source maintainer - no pressure.
I've just set up Immich today along with my dad, and we're absolutely delighted. Thank you for all the good work; I didn't expect feature parity with Google Photos, but hey - here we are!

**Comment by dkerlee** [comment]
I wanted to echo some of this too.

Picture + audio = video = included
Picture = included
Audio = not included

Get another app to add a single picture to the audio? = video = included.

This is (another) opportunity to set ourselves apart other picture hosting packages out there.

**My creative feeling on it:**
There's something really special about listening to yourself, or a friend, share a story, tell a joke, or recount an event. Like a black and white photo: it requires the viewer or listener, to draw on their own memories and intermix them with what they're consuming. This makes the memory special, and brings that person back to that moment, sharing that moment with whomever is talking. If you haven't tried recording a long-ish audio file for a friend or family member: try it out. It really is a neat medium; and I think you'll be surprised how well it works with our 

**How I imagine it looking in the timeline:**
If it's just an audio file, you could optionally include visualizations that can be on or off. An EQ bar, an old winamp visualization, blackness, or photo. I imagine the audio file has a date and time stamp and it takes up one square in a larger album of assets.

**A usage example:**
I am sharing an album with my brother where we upload videos to one another. Frequently the videos are just of the sky as we are on a walk, or our drunk faces during a blather. Sometimes I like to yarn on and on, and I don't want to be on video. I just want to talk, and be listened to. So I have to record a video of the floor to fit into Immich. If you haven't tried recording a long-ish audio file for a friend or family member: try it out. It really is a neat medium; and I think you'll be surprised how well it works with our brains.

**Comment by jfwerner** [comment]
Until this maybe happens sometime in the future, a quick and dirty solution I use is to rename an audio file to mp4 and upload it to Immich. I tried this with an .aac file recorded using the recorder app on a Nothing phone.
What works:
- Uploading (from phone by selecting file and sharing to immich)
- Playing on Immich Android App
- Playing on web interface (Firefox on Windows 11)
- Pausing and playing the "video"
- Description text

Limitations:
- No scrolling in the "video", only linear playback
- No thumbnail (duh)

No guarantees for this, don't expect this to keep working or use this as a backup solution for audio.

**Comment by forresthopkinsa** [comment]
@jfwerner You're creating malformed mp4 files – if you want to put an AAC stream in an MP4 container, you can very easily do that by remuxing, e.g. `ffmpeg -i my-audio.aac -c:a copy my-audio.mp4`

This will not re-encode the audio stream, it will just copy it into a mp4 container.

In my testing, Immich tolerates malformed files like what you're describing, but it gets confused and the player struggles more with it.

**Comment by jfwerner** [comment]
@forresthopkinsa I'm aware this is not really a good idea, but it's a quick workaround and works from a phone in just a second. Thanks for the clarification and the example though!

**Comment by jdyyc** [comment]
Is this fully closed?

I have another use case for this.   I would like to be able to attach WAV files to videos.

When used with external (wireless) mics, the Osmo Pocket 3 will save the mic's audio as part of the video, but it'll also drop a separate WAV file that is the audio captured off the built in mics.

So when I archive my OP3 videos to immich, I'm left with this WAV file that I would like to be associated with and saved along side the original video.

A little different than standalone audio uploads.  Maybe a bit niche.   But still would be nice :)

**Comment by niieani** [comment]
I agree, besides archiving voice memos and audio recordings, I also have the use case of attaching secondary microphone audio to existing video files. I'd say this warrants a separate github issue @jdyyc - if you make one I'd be happy to add my support there too.

**Comment by sirwilliamdev** [comment]
hey there folks! 😄
related to this topic, I found myself in the same situation and realised there wasn’t any open-source option for storing personal recordings, so I created one myself and have been using it for a few weeks now.
For anyone who might be interested, here’s the link so you can have a look: https://github.com/resonand-app/resonand
Comments and feedback are welcome 🙃
