### ISSUE TITLE
[Feature]: Option to use a Photoprism-like directory structure for storing images - i.e Multiple level directory vs flat directory.

### ISSUE THREAD

**Issue by danielyrovas** [immich-app/immich#402]
### Feature detail

Photoprism utilises a very nice directory structure for storing images, this could be adapted to be per user so that it works nicely with Immich
Photoprism structure for an image:
```
/2018/01/20180130_151510_861DFD74.jpg
```
which I think translates to
```
/yyyy/mm/yyyymmdd_hhmmss_<unique image tag>.filetype
```
Proposed structure for Immich
```
/username/original/yyyy/mm/yyyymmdd_hhmmss_<unique image tag>.filetype
/username/thumb/yyyy/mm/yyyymmdd_hhmmss_<unique image tag>.filetype
```
If the usernames need a unique tag that could also be added after the username.

This would allow the images that are stored on the server to be far more portable between services and help people understand how the images are being stored.

### Platform

Server

**Comment by bo0tzz** [comment]
Duplicate: #34

**Comment by alextran1502** [comment]
@danielyrovas Hi Daniel, right now we are weighing the difference between storing in a flat directory or vs multiple-level directory regarding the reading speed when browsing the images. I like your proposal since it is easier for people who access the file on disk, but I am not sure it will be the best in terms of performance. I and the team will take a look at this in the future and let you know. I will leave this issue open for now

**Comment by danielyrovas** [comment]
Could performance be improved by using a flat directory for the thumbnails but a multiple level directory for images?

Thanks for your work on this, I've been enjoying it so far - much more user friendly for my parents and relatives than the syncthing + photoprism stack I was running before.

**Comment by alextran1502** [comment]
Thank you for the feedback, it's always nice to know that the app is helping others as well. The flat directory performance gain is what we assume, there hasn't been any benchmarking yet. I will keep you update when we move to work on this

**Comment by alextran1502** [comment]
Implemented
