### ISSUE TITLE
[Feature]: Only upload on wifi connection

### ISSUE THREAD

**Issue by MalteKiefer** [immich-app/immich#421]
### Feature detail

In the settings we should set up an option that allows the user to upload images only when there is a wifi connection.

### Platform

Mobile App

**Comment by zoodyy** [comment]
Works on Android with #382 the new background upload

**Comment by zackpollard** [comment]
Closing this as it is implemented for android background uploading and will be implemented when iOS background uploading exists in #235

**Comment by Batwam** [comment]
> Closing this as it is implemented for android background uploading and will be implemented when iOS background uploading exists in #235 

I don't believe that this issue is closed. While it is a great feature, I don't be believing allowing background uploads really the same thing as allowing upload on wifi only?

I'm taking about something like this: ![image](https://github.com/immich-app/immich/assets/56710655/e5f958d1-a469-4799-a8fc-86eac13c18b7)

**Comment by miltiad** [comment]
Agreed with the above post

**Comment by evulhotdog** [comment]
@zackpollard can we re-open this?
