### ISSUE TITLE
[BUG] delete on webinterface wont delete on all other devices

### ISSUE THREAD

**Issue by CurlyFlow** [immich-app/immich#4520]
### The bug

So im goin to webinterface, delete something and as soon as the next backup cycle happens, there all back, i would expect them to be gone EVERYWHERE, like its with gphotos...

I guess if i delete on mobile, it goes away from all other devices?

### The OS that Immich Server is running on

unraid 6.12.4

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
Hello, we don't have the blacklist to avoid reuploading the assets yet

**Comment by alextran1502** [comment]
Do you mean deleting from the web will also delete the photo on both Immich and your phone's file system? If the answer is yes, then it is impossible because to delete on the device, the OS will prompt you if you want to delete the photos from the app. This mechanism from the OS is to prevent bad actor apps from removing photos without your consent

**Comment by alextran1502** [comment]
I assume they have access to internal API to bypass the OS prompt since it is within Google-Android ecosystem
