### ISSUE TITLE
[Feature]: support dropbox as file storage system

### ISSUE THREAD

**Issue by chyroc** [immich-app/immich#466]
### Feature detail

support upload file and download file from dropbox.

### Platform

Server

**Comment by bo0tzz** [comment]
You can [mount your Dropbox as a folder](https://thelig.ht/code/dbxfs/) and then use that as your library storage location. Expect it to be slow compared to using local storage though.

**Comment by zackpollard** [comment]
Bo0tzz advice is probably your best bet, we don't plan to directly integrate with any providers as of now as that is not the vision for Immich currently.

**Comment by koalp** [comment]
Hello, 
I’m answering this issue instead of opening a discussion because I had a similar idea but I understand that it is not planned.

When I saw “external libraries”, I thought that it was a feature to integrate with external storage or cloud providers. It could allow a person that chooses to stores their picture on nextcloud/dropbox/onedrive/… to participate to shared albums with people that are using immich without reuploading all their pictures.

I understand if it is never planned as it would be complicated to implement : there are many different providers, each one requiring a different abstraction, and there would be caching and replication issues.
