### ISSUE TITLE
[BUG] getServerStatistics URL changed in v1.85.0

### ISSUE THREAD

**Issue by gabe565** [immich-app/immich#4897]
### The bug

I just upgraded to v1.85.0 and noticed the `getServerStatistics` URL changed from `/api/server-info/stats` to `/api/server-info/statistics` in #4817. I wanted to check early on to ensure that change was intended. If so, feel free to close this issue, but it's a breaking change that I'm hoping just got lost in the PR changes. An example of an affected app is here gethomepage/homepage#2282

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

v1.84.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Upgrade to Immich v1.85.0
2. Existing API integrations do not work
```

**Comment by jrasm91** [comment]
Yes this was intentional, just missed adding it to the release notes.

**Comment by jrasm91** [comment]
We have several "statistics" endpoints in the API, including the following:
```
/activity/statistics
/asset/statistics
/library/:id/statistics
/person/:id/statistics
```

They all use full "statistics", with exception of the server-info endpoint, so that was changed to align with everything else.

Sorry for missing it in the release notes. We have only been listing breaking changes for our own clients, but obviously there are other applications that rely on the Immich API as well. We'll try to include all API changes in the notes moving forwards.

It looks like the upstream issue has already been addressed, so I will go ahead and close this, as it was an intended change.

**Comment by shamoon** [comment]
Indeed we’ve solved it, though it does require an extra api call to check the version first (but happy that endpoint exists to do so).

just one other thought would be to include some kind of alias or redirect for the old URL to maintain backwards compatibility in a situation like this
