### ISSUE TITLE
Clean up unnecessarily transcoded videos

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#5873]
When an admin changes the video transcoding settings, it's possible to end up with assets that still have a transcoded video file even though according to the new settings they shouldn't. When running the transcoding job, if it is determined that [a transcode is not required](https://github.com/immich-app/immich/blob/main/server/src/domain/media/media.service.ts#L246-L249), the code should clean up the existing transcode file if there is one and remove the path from the database.

**Comment by Batwam** [comment]
I would personally prefer to keep already transcoded videos and only skip transcoding for future assets. This would be consistent with the way pictures are only rearranged when "Storage Template Migration" is clicked.

Therefore, rather than deleting all transcoded videos right away, I believe that the correct behaviour would be to only delete previously transcoded videos if the user voluntarily clicks on "ALL" under Transcoded Videos"?

**Comment by bo0tzz** [comment]
> the correct behaviour would be to only delete previously transcoded videos if the user voluntarily clicks on "ALL" under Transcoded Videos"

That would be the behaviour with this change. The file would only get deleted when running the job, which in turn would only happen if you click "ALL"

**Comment by Batwam** [comment]
I was wondering actually, are transcoded videos currently deleted if a video is no longer in the library (either because they have been moved by the user or deleted within the app)?

**Comment by bo0tzz** [comment]
Yes: 
https://github.com/immich-app/immich/blob/dea1063b17ef24e3a9616953d5279e6f2a19425f/server/src/domain/asset/asset.service.ts#L489-L496
