### ISSUE TITLE
[Feature]: Photo editor

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#768]
### Feature detail

I don't know if this is out of the project's scope, but I would like to have the ability to edit photos.
The ability to crop, rotate, mirror, change brightness, change contrast, and add filters.
I chose the platform mobile, but it would be nice for both the website and mobile.

### Platform

Mobile App

**Comment by alextran1502** [comment]
Not within the scope of what we want to do

**Comment by it-guy92** [comment]
I would love to see some very Basic editing features. Like cropping oder rotating images. 

Without these its difficult to replace google photos.

**Comment by enboig** [comment]
Rotate would be enough for me, for to many old photos which need fixing; I suppose I will need to use digikam to fix them first

**Comment by Sniper435** [comment]
I would second a request to be able to fix image rotation, more complex editing is not something I generally feel the need for within immich but being able to fix incorrectly rotated photos would be greatly appreciated.

**Comment by bcsteeve** [comment]
+1 for rotate.

**Comment by CyberSardinha** [comment]
For me gps coordenate fixing would be great. I have about 30/40 photos that show in the middle of the ocean -.-

**Comment by linuxturtle** [comment]
It's a shame this is closed.  There's no way I can replace google photos without being able to rotate & crop at least.  Pretty much a hard requirement from the spousal unit for any attempt to self-host photos.

**Comment by bcsteeve** [comment]
Agree.  I think they'll get there eventually, and the dev team here has been pretty responsive. In particular, they seem willing to include things that Google Photos has, and GP definitely has the ability to rotate and add in missing location data.

**Comment by Watever44** [comment]
I don't know how that would be done and what help can be done but it would something good to have.

**Comment by phellarv** [comment]
+1 for very basic editing: Rotate, Crop and Mirror.

**Comment by naosense** [comment]
+1 rotate

**Comment by Tanja-4732** [comment]
> Not within the scope of what we want to do

(see https://github.com/immich-app/immich/issues/768#issuecomment-1366129894)

---

While I do agree with this sentiment, simple rotate (the kind of thing that only does four possible rotations) really is essential;

See #3271 for a possible implementation (though I don't know how far that PR got).

In any case, huge thanks to all contributors, especially @alextran1502 for your time & effort :tada: :sparkling_heart:

**Comment by alextran1502** [comment]
@Tanja-4732 scopes have changed since then, and it makes sense now to have some basic editing in Immich

**Comment by Tanja-4732** [comment]
> @Tanja-4732 scopes have changed since then, and it makes sense now to have some basic editing in Immich

Thanks for responding @alextran1502 :blush: 

Do you want to re-open this one now?

**Comment by alextran1502** [comment]
@Tanja-4732 there is a PR in progress so we don't need to reopen this

**Comment by Tanja-4732** [comment]
ok :+1:

**Comment by jonhnet** [comment]
I'm delighted to hear simple (and hopefully nondestructive) editing is back on the menu. As with others, this is the one big blocker that I use heavily in GP.

I suspect part of the issue is avoiding feature creep. I propose that there's a distinction between edits applied to >5% of kept images vs. rare edits that need the rich features of Gimp or Photoshop.

For me, crop is essential; I suspect more than half of the images I care about (put in an album or share) get cropped. My "everyday carry" list would be:

- crop,
- straighten,
- brightness/contrast/shadow brightness,
- 90° rotate

Having those be available in-app (in-browser), nondestructive, propagated to albums (like they are in G Photos) would be fantastically useful. The remaining cases are <0.1% of images I care about, at which point the burden of using an external editor and managing a destructively-edited copy are acceptable costs for very special images.

I'm hoping this suggestion reduces the threat of feature creep and makes the feature request more viable.

**Comment by aisbergde** [comment]
> @Tanja-4732 there is a PR in progress so we don't need to reopen this

which PR? 
to be able to read and follow

**Comment by jrasm91** [comment]
It is the oldest one :-)

#3271
