### ISSUE TITLE
[Feature]: Manual Connection to Local IP/Domain

### ISSUE THREAD

**Issue by Trancep0rt** [immich-app/immich#817]
### Feature detail

ATM is only possible to configure one domain for immichs app.
I´m using Cloudflares Argo tunnel, which means using my domain, every traffic runs over WAN -> Cloudflare -> WAN, even if i´m in the same network as immich-server.

It would be awesome to have a optional local IP/domain (like Plex has, "manual Connections") that is checked and used if you´re in -home wlan-

### Platform

Mobile App

**Comment by zackpollard** [comment]
Hey! I don't think this is something we currently plan for, my opinion on the matter would be that this can be resolved through the user of local DNS so that when you're in your local network, your external domain resolves to your servers internal IP, so instead of connecting externally it will just connect directly to that server. I'm not sure how the cloudflare argo tunnel will interact with this but I wouldn't expect it to cause a problem 😄

**Comment by bo0tzz** [comment]
There was previously an issue for this in #308 , which we closed for the reason Zack described.
